### ISSUE TITLE
Change type to _doc

### ISSUE THREAD

**Issue by aleph-zero** [cloudflare/cloudflare-elastic#1]
Change dashboards and index templates to use _doc for the document type in preparation for supporting Elasticsearch 7.x.

**Comment by jbow** [comment]
Alternatively you can just remove doc{ ... } in the index template.

**Comment by jbow** [comment]
The Lambda is failing for Elasticsearch 7.x - Lambda is returning: 
WARNING: request [POST https://[elasticinstance].us-west-1.aws.found.io:9243/_bulk?timeout=1m] returned 1 warnings: [299 Elasticsearch-7.2.0-508c38a "[types removal] Specifying types in bulk requests is deprecated."]

failure in bulk execution:
[0]: index [cloudflare], type [doc], id [null], message [ElasticsearchException[Elasticsearch exception [type=exception, reason=java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: unable to parse date [2019-06-27T01:05:32Z]]]
...
[99]

**Comment by aleph-zero** [comment]
@jbow I'm working on getting support for 7.x. Hope to have it out soon.

**Comment by jbow** [comment]
Is there an update on this? Thanks!!

**Comment by aleph-zero** [comment]
@jbow Support for Elastic 7.x is complete. 
https://github.com/cloudflare/cloudflare-elastic/releases/tag/7.x
